apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base-helm
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
  project: default
  source:
    chart: istio/base
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.18.1
    helm:
      releaseName: istio-base
      values: |
        defaultRevision: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true