apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugparty-game-server
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-server
  template:
    metadata:
      labels:
        app: game-server
    spec:
      containers:
        - name: game-server
          image: us-east1-docker.pkg.dev/bug-party-dev/bug-party-dev/game-server:v0.2.3
          env:
          - name: DB_HOST
            value: "bugparty-redis.default.svc.cluster.local"
          - name: PERSIST_GAME_STATE
          value: "true"
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bugparty-game-server
  namespace: default
labels:
  app: game-server
spec:
  selector:
    app: game-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
# TODO -- need to productionize this
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugparty-redis
  namespace: default
labels:
  app: bugparty-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bugparty-redis
  template:
    metadata:
      labels:
        app: bugparty-redis
    spec:
      containers:
      - name: redis
        image: redis:6.2.5
        ports:
        - containerPort: 6379
        # TODO add resouce limits etc.
        
---
apiVersion: v1
kind: Service
metadata:
  name: bugparty-redis
  namespace: default
  labels:
    app: bugparty-redis
spec:
  selector:
    app: bugparty-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
