apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugparty-game-server
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-server
  template:
    metadata:
      labels:
        app: game-server
    spec:
      containers:
        - name: game-server
          image: us-east1-docker.pkg.dev/bug-party-dev/bug-party-dev/game-server:v0.2.3
          ports:
          - containerPort: 8080
---
apiVerson: v1
kind: Service
metadata:
  name: bugparty-game-server
  namespce: default
labels:
  app: game-server
spec:
  selector:
    app: game-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080