apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-container
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep-container
  template:
    metadata:
      labels:
        app: sleep-container
    spec:
      containers:
        - name: sleep
          image: us-east1-docker.pkg.dev/bug-party-dev/bug-party-dev/game-server:v0.1.2
          command: ["sleep", "3600"]
          env: 
          - key: "hello"
            value: "world"
