apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: istio-system
spec:
  acme:
    email: albert.lockett@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: istio
          podTemplate:
            metadata:
              labels:
                cm-challenge: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: cm-challenge-solvers
  namespace: istio-system
spec:
  selector:
    cm-challenge: "true"
  ports:
  - name: http
    port: 8089
    targetPort: 8089
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
  # -- todo, this might mess w/ SDS and cert rotation
  # when troubleshooting future erros, can remove this?
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
spec:
  secretName: ingress-cert-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - api.bugparty.net
  - auth.bugparty.net
  - grafana.bugparty.net
  - prometheus.bugparty.net
