apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stage
  namespace: istio-system
spec:
  acme:
    email: albert.lockett@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-stage
    solvers:
    - http01:
        ingress:
          class: istio
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
spec:
  secretName: ingress-cert-stage
  issuerRef:
    name: letsencrypt-stage
    kind: ClusterIssuer
  # commonName: 
  dnsNames:
  - api.bugparty.net
  # - auth.bugparty.net
  # - grafana.bugparty.net
  # - prometheus.bugparty.net
---
# required for the http 01 challenge
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
  namespace: istio-system
spec:
  controller: istio.io/ingress-controller