apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: "https://kubernetes.default.svc"
  project: default
  source:
    chart: cert-manager
    path: k8s/argo/cert-manager.yaml
    repoURL: https://charts.jetstack.io
    targetRevision: 1.12.4
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certs
  namespace: argocd
spec:
  destination:
    namespace: certs
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: k8s/apps/certs
    repoURL: https://github.com/Bug-Party/infra.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
