apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-helm
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.58.8
    helm:
      releaseName: grafana
      values: |
        plugins: "grafana-kubernetes-app"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-dashboards
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability
  project: default
  source:
    repoURL: "https://github.com/Bug-Party/infra"
    path: "k8s/apps/grafana/dashboards/generated"
    targetRevision: HEAD
