apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base-helm
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
  project: default
  source:
    chart: base
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.18.1
    helm:
      releaseName: istio-base
      values: |
        defaultRevision: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod-helm
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
  project: default
  source:
    chart: istiod
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.18.1
    helm:
      releaseName: istiod
      values: |
        pilot:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
        meshConfig:
          extensionProviders:
          - name: "oauth2-proxy"
            envoyExtAuthzHttp:
              service: "ouath-proxy-oauth2-proxy.istio-system.svc.cluster.local"
              port: "4180" 
              includeHeadersInCheck:
              - authorizationcookie
              - cookie 
              headersToUpstreamOnAllow: 
              - authorization
              - path
              - x-auth-request-user
              - x-auth-request-email
              - x-auth-request-access-token
              headersToDownstreamOnDeny:
              - content-type
              - set-cookie
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress-helm
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
  project: default
  source:
    chart: gateway
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.18.1
    helm:
      releaseName: istio-ingress
      values: |
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-config
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/apps/istio
    repoURL: https://github.com/Bug-Party/infra.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - Validate=false
