apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth-proxy-helm
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
  project: default
  source:
    chart: oauth2-proxy
    repoURL: https://oauth2-proxy.github.io/manifests
    targetRevision: 6.16.1
    helm:
      releaseName: oauth-proxy
      values: |
        config:
          clientID: 8d511eb2aedc6a92e7df
          clientSecret: f9de6cfadffb7e3c2957918e6e906e055a2e0aa2
          cookieSecret: ZlE3VzZLbFNndWRudEpjTGgxY2tpejc1cW04eTlId1U=
        extraArgs:
          cookie-domain: "*.bugparty.net"
          cookie-secure: "false"
          # TODO -- once we have https enabledd we need to change this to https:
          redirect-url: http://prometheus.bugparty.net/oauth2/callback
          provider: github
          scope: "user:email"
          github-org: Bug-Party
          upstream: static://200
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

